//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using SmartWorking.Office.PrimitiveEntities;

namespace SmartWorking.Office.Entities
{
    public partial class Building : BuildingPrimitive
    {
        #region Navigation Properties
    
        public ICollection<ClientBuilding> ClientBuildings
        {
            get
            {
                if (_clientBuildings == null)
                {
                    var newCollection = new FixupCollection<ClientBuilding>();
                    newCollection.CollectionChanged += FixupClientBuildings;
                    _clientBuildings = newCollection;
                }
                return _clientBuildings;
            }
            set
            {
                if (!ReferenceEquals(_clientBuildings, value))
                {
                    var previousValue = _clientBuildings as FixupCollection<ClientBuilding>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupClientBuildings;
                    }
                    _clientBuildings = value;
                    var newValue = value as FixupCollection<ClientBuilding>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupClientBuildings;
                    }
                }
            }
        }
        private ICollection<ClientBuilding> _clientBuildings;

        #endregion
        #region Association Fixup
    
        private void FixupClientBuildings(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ClientBuilding item in e.NewItems)
                {
                    item.Building = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ClientBuilding item in e.OldItems)
                {
                    if (ReferenceEquals(item.Building, this))
                    {
                        item.Building = null;
                    }
                }
            }
        }

        #endregion
    }
}
