//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using SmartWorking.Office.PrimitiveEntities;

namespace SmartWorking.Office.Entities
{
    public partial class Car : CarPrimitive
    {
        #region Primitive Properties
    		public override Nullable<int> Driver_Id
    		{
            get { return _driver_Id; }
            set
            {        
                try
                {
                    _settingFK = true;
                    if (_driver_Id != value)
                    {
                        if (Driver != null && Driver.Id != value)
                        {
                            Driver = null;
                        }
                        _driver_Id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
    		}
    		private Nullable<int> _driver_Id;    
    

        #endregion
        #region Navigation Properties
    
        public Driver Driver
        {
            get { return _driver; }
            set
            {
                if (!ReferenceEquals(_driver, value))
                {
                    var previousValue = _driver;
                    _driver = value;
                    FixupDriver(previousValue);
                }
            }
        }
        private Driver _driver;
    
        public ICollection<DeliveryNote> DeliveryNotes
        {
            get
            {
                if (_deliveryNotes == null)
                {
                    var newCollection = new FixupCollection<DeliveryNote>();
                    newCollection.CollectionChanged += FixupDeliveryNotes;
                    _deliveryNotes = newCollection;
                }
                return _deliveryNotes;
            }
            set
            {
                if (!ReferenceEquals(_deliveryNotes, value))
                {
                    var previousValue = _deliveryNotes as FixupCollection<DeliveryNote>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupDeliveryNotes;
                    }
                    _deliveryNotes = value;
                    var newValue = value as FixupCollection<DeliveryNote>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupDeliveryNotes;
                    }
                }
            }
        }
        private ICollection<DeliveryNote> _deliveryNotes;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupDriver(Driver previousValue)
        {
            if (previousValue != null && previousValue.Cars.Contains(this))
            {
                previousValue.Cars.Remove(this);
            }
    
            if (Driver != null)
            {
                if (!Driver.Cars.Contains(this))
                {
                    Driver.Cars.Add(this);
                }
                if (Driver_Id != Driver.Id)
                {
                    Driver_Id = Driver.Id;
                }
            }
            else if (!_settingFK)
            {
                Driver_Id = null;
            }
        }
    
        private void FixupDeliveryNotes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (DeliveryNote item in e.NewItems)
                {
                    item.Car = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (DeliveryNote item in e.OldItems)
                {
                    if (ReferenceEquals(item.Car, this))
                    {
                        item.Car = null;
                    }
                }
            }
        }

        #endregion
    }
}
