//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using SmartWorking.Office.PrimitiveEntities;

namespace SmartWorking.Office.Entities
{
    public partial class CarType : CarTypePrimitive
    {
        #region Primitive Properties
    		public override int Id
    		{
            get { return _id; }
            set
            {        
                if (_id != value)
                {
                    if (Car != null && Car.Id != value)
                    {
                        Car = null;
                    }
                    _id = value;
                }
            }
    		}
    		private int _id;    
    

        #endregion
        #region Navigation Properties
    
        public Car Car
        {
            get { return _car; }
            set
            {
                if (!ReferenceEquals(_car, value))
                {
                    var previousValue = _car;
                    _car = value;
                    FixupCar(previousValue);
                }
            }
        }
        private Car _car;

        #endregion
        #region Association Fixup
    
        private void FixupCar(Car previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.CarType, this))
            {
                previousValue.CarType = null;
            }
    
            if (Car != null)
            {
                Car.CarType = this;
                if (Id != Car.Id)
                {
                    Id = Car.Id;
                }
            }
        }

        #endregion
    }
}
