//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SmartWorking.Office.Entities
{
    public partial class Contractor
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public string FullName
        {
            get;
            set;
        }
    
        public string Name
        {
            get;
            set;
        }
    
        public string Surname
        {
            get;
            set;
        }
    
        public string Phone
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public ICollection<Building> Buildings
        {
            get
            {
                if (_buildings == null)
                {
                    var newCollection = new FixupCollection<Building>();
                    newCollection.CollectionChanged += FixupBuildings;
                    _buildings = newCollection;
                }
                return _buildings;
            }
            set
            {
                if (!ReferenceEquals(_buildings, value))
                {
                    var previousValue = _buildings as FixupCollection<Building>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupBuildings;
                    }
                    _buildings = value;
                    var newValue = value as FixupCollection<Building>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupBuildings;
                    }
                }
            }
        }
        private ICollection<Building> _buildings;

        #endregion
        #region Association Fixup
    
        private void FixupBuildings(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Building item in e.NewItems)
                {
                    item.Contractor = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Building item in e.OldItems)
                {
                    if (ReferenceEquals(item.Contractor, this))
                    {
                        item.Contractor = null;
                    }
                }
            }
        }

        #endregion
    }
}
