//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SmartWorkingModel", "FK_Buildings_Contractors", "Contractor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SmartWorking.Office.Model.Contractor), "Building", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SmartWorking.Office.Model.Building), true)]
[assembly: EdmRelationshipAttribute("SmartWorkingModel", "FK_DeliveryNotes_Buildings", "Building", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SmartWorking.Office.Model.Building), "DeliveryNote", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SmartWorking.Office.Model.DeliveryNote), true)]
[assembly: EdmRelationshipAttribute("SmartWorkingModel", "FK_DeliveryNotes_Cars", "Car", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SmartWorking.Office.Model.Car), "DeliveryNote", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SmartWorking.Office.Model.DeliveryNote), true)]
[assembly: EdmRelationshipAttribute("SmartWorkingModel", "FK_DeliveryNotes_Drivers", "Driver", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SmartWorking.Office.Model.Driver), "DeliveryNote", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SmartWorking.Office.Model.DeliveryNote), true)]
[assembly: EdmRelationshipAttribute("SmartWorkingModel", "FK_DeliveryNotes_Recipes", "Recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SmartWorking.Office.Model.Recipe), "DeliveryNote", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SmartWorking.Office.Model.DeliveryNote), true)]
[assembly: EdmRelationshipAttribute("SmartWorkingModel", "FK_MaterialStocks_Materails", "Material", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SmartWorking.Office.Model.Material), "MaterialStock", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SmartWorking.Office.Model.MaterialStock), true)]
[assembly: EdmRelationshipAttribute("SmartWorkingModel", "FK_RecipeSpecifications_Materials", "Material", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SmartWorking.Office.Model.Material), "RecipeSpecification", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SmartWorking.Office.Model.RecipeSpecification), true)]
[assembly: EdmRelationshipAttribute("SmartWorkingModel", "FK_RecipeSpecifications_Recipes", "Recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SmartWorking.Office.Model.Recipe), "RecipeSpecification", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SmartWorking.Office.Model.RecipeSpecification), true)]

#endregion

namespace SmartWorking.Office.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SmartWorkingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SmartWorkingEntities object using the connection string found in the 'SmartWorkingEntities' section of the application configuration file.
        /// </summary>
        public SmartWorkingEntities() : base("name=SmartWorkingEntities", "SmartWorkingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SmartWorkingEntities object.
        /// </summary>
        public SmartWorkingEntities(string connectionString) : base(connectionString, "SmartWorkingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SmartWorkingEntities object.
        /// </summary>
        public SmartWorkingEntities(EntityConnection connection) : base(connection, "SmartWorkingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Building> Buildings
        {
            get
            {
                if ((_Buildings == null))
                {
                    _Buildings = base.CreateObjectSet<Building>("Buildings");
                }
                return _Buildings;
            }
        }
        private ObjectSet<Building> _Buildings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Car> Cars
        {
            get
            {
                if ((_Cars == null))
                {
                    _Cars = base.CreateObjectSet<Car>("Cars");
                }
                return _Cars;
            }
        }
        private ObjectSet<Car> _Cars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contractor> Contractors
        {
            get
            {
                if ((_Contractors == null))
                {
                    _Contractors = base.CreateObjectSet<Contractor>("Contractors");
                }
                return _Contractors;
            }
        }
        private ObjectSet<Contractor> _Contractors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DeliveryNote> DeliveryNotes
        {
            get
            {
                if ((_DeliveryNotes == null))
                {
                    _DeliveryNotes = base.CreateObjectSet<DeliveryNote>("DeliveryNotes");
                }
                return _DeliveryNotes;
            }
        }
        private ObjectSet<DeliveryNote> _DeliveryNotes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Driver> Drivers
        {
            get
            {
                if ((_Drivers == null))
                {
                    _Drivers = base.CreateObjectSet<Driver>("Drivers");
                }
                return _Drivers;
            }
        }
        private ObjectSet<Driver> _Drivers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Material> Materials
        {
            get
            {
                if ((_Materials == null))
                {
                    _Materials = base.CreateObjectSet<Material>("Materials");
                }
                return _Materials;
            }
        }
        private ObjectSet<Material> _Materials;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MaterialStock> MaterialStocks
        {
            get
            {
                if ((_MaterialStocks == null))
                {
                    _MaterialStocks = base.CreateObjectSet<MaterialStock>("MaterialStocks");
                }
                return _MaterialStocks;
            }
        }
        private ObjectSet<MaterialStock> _MaterialStocks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Recipe> Recipes
        {
            get
            {
                if ((_Recipes == null))
                {
                    _Recipes = base.CreateObjectSet<Recipe>("Recipes");
                }
                return _Recipes;
            }
        }
        private ObjectSet<Recipe> _Recipes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RecipeSpecification> RecipeSpecifications
        {
            get
            {
                if ((_RecipeSpecifications == null))
                {
                    _RecipeSpecifications = base.CreateObjectSet<RecipeSpecification>("RecipeSpecifications");
                }
                return _RecipeSpecifications;
            }
        }
        private ObjectSet<RecipeSpecification> _RecipeSpecifications;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Buildings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBuildings(Building building)
        {
            base.AddObject("Buildings", building);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCars(Car car)
        {
            base.AddObject("Cars", car);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contractors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContractors(Contractor contractor)
        {
            base.AddObject("Contractors", contractor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DeliveryNotes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDeliveryNotes(DeliveryNote deliveryNote)
        {
            base.AddObject("DeliveryNotes", deliveryNote);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Drivers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDrivers(Driver driver)
        {
            base.AddObject("Drivers", driver);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Materials EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMaterials(Material material)
        {
            base.AddObject("Materials", material);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MaterialStocks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMaterialStocks(MaterialStock materialStock)
        {
            base.AddObject("MaterialStocks", materialStock);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Recipes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecipes(Recipe recipe)
        {
            base.AddObject("Recipes", recipe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RecipeSpecifications EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecipeSpecifications(RecipeSpecification recipeSpecification)
        {
            base.AddObject("RecipeSpecifications", recipeSpecification);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SmartWorkingModel", Name="Building")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Building : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Building object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="contractor_Id">Initial value of the Contractor_Id property.</param>
        public static Building CreateBuilding(global::System.Int32 id, global::System.Int32 contractor_Id)
        {
            Building building = new Building();
            building.Id = id;
            building.Contractor_Id = contractor_Id;
            return building;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Contractor_Id
        {
            get
            {
                return _Contractor_Id;
            }
            set
            {
                OnContractor_IdChanging(value);
                ReportPropertyChanging("Contractor_Id");
                _Contractor_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Contractor_Id");
                OnContractor_IdChanged();
            }
        }
        private global::System.Int32 _Contractor_Id;
        partial void OnContractor_IdChanging(global::System.Int32 value);
        partial void OnContractor_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Street
        {
            get
            {
                return _Street;
            }
            set
            {
                OnStreetChanging(value);
                ReportPropertyChanging("Street");
                _Street = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Street");
                OnStreetChanged();
            }
        }
        private global::System.String _Street;
        partial void OnStreetChanging(global::System.String value);
        partial void OnStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HouseNo
        {
            get
            {
                return _HouseNo;
            }
            set
            {
                OnHouseNoChanging(value);
                ReportPropertyChanging("HouseNo");
                _HouseNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HouseNo");
                OnHouseNoChanged();
            }
        }
        private global::System.String _HouseNo;
        partial void OnHouseNoChanging(global::System.String value);
        partial void OnHouseNoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_Buildings_Contractors", "Contractor")]
        public Contractor Contractor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contractor>("SmartWorkingModel.FK_Buildings_Contractors", "Contractor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contractor>("SmartWorkingModel.FK_Buildings_Contractors", "Contractor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contractor> ContractorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contractor>("SmartWorkingModel.FK_Buildings_Contractors", "Contractor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contractor>("SmartWorkingModel.FK_Buildings_Contractors", "Contractor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_DeliveryNotes_Buildings", "DeliveryNote")]
        public EntityCollection<DeliveryNote> DeliveryNotes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DeliveryNote>("SmartWorkingModel.FK_DeliveryNotes_Buildings", "DeliveryNote");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DeliveryNote>("SmartWorkingModel.FK_DeliveryNotes_Buildings", "DeliveryNote", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SmartWorkingModel", Name="Car")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Car : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Car object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Car CreateCar(global::System.Int32 id)
        {
            Car car = new Car();
            car.Id = id;
            return car;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegistrationNumber
        {
            get
            {
                return _RegistrationNumber;
            }
            set
            {
                OnRegistrationNumberChanging(value);
                ReportPropertyChanging("RegistrationNumber");
                _RegistrationNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RegistrationNumber");
                OnRegistrationNumberChanged();
            }
        }
        private global::System.String _RegistrationNumber;
        partial void OnRegistrationNumberChanging(global::System.String value);
        partial void OnRegistrationNumberChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_DeliveryNotes_Cars", "DeliveryNote")]
        public EntityCollection<DeliveryNote> DeliveryNotes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DeliveryNote>("SmartWorkingModel.FK_DeliveryNotes_Cars", "DeliveryNote");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DeliveryNote>("SmartWorkingModel.FK_DeliveryNotes_Cars", "DeliveryNote", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SmartWorkingModel", Name="Contractor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contractor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contractor object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Contractor CreateContractor(global::System.Int32 id)
        {
            Contractor contractor = new Contractor();
            contractor.Id = id;
            return contractor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Surname
        {
            get
            {
                return _Surname;
            }
            set
            {
                OnSurnameChanging(value);
                ReportPropertyChanging("Surname");
                _Surname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Surname");
                OnSurnameChanged();
            }
        }
        private global::System.String _Surname;
        partial void OnSurnameChanging(global::System.String value);
        partial void OnSurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_Buildings_Contractors", "Building")]
        public EntityCollection<Building> Buildings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Building>("SmartWorkingModel.FK_Buildings_Contractors", "Building");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Building>("SmartWorkingModel.FK_Buildings_Contractors", "Building", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SmartWorkingModel", Name="DeliveryNote")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DeliveryNote : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DeliveryNote object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static DeliveryNote CreateDeliveryNote(global::System.Int32 id)
        {
            DeliveryNote deliveryNote = new DeliveryNote();
            deliveryNote.Id = id;
            return deliveryNote;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Building_Id
        {
            get
            {
                return _Building_Id;
            }
            set
            {
                OnBuilding_IdChanging(value);
                ReportPropertyChanging("Building_Id");
                _Building_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Building_Id");
                OnBuilding_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Building_Id;
        partial void OnBuilding_IdChanging(Nullable<global::System.Int32> value);
        partial void OnBuilding_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Recipe_Id
        {
            get
            {
                return _Recipe_Id;
            }
            set
            {
                OnRecipe_IdChanging(value);
                ReportPropertyChanging("Recipe_Id");
                _Recipe_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Recipe_Id");
                OnRecipe_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Recipe_Id;
        partial void OnRecipe_IdChanging(Nullable<global::System.Int32> value);
        partial void OnRecipe_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private Nullable<global::System.Double> _Amount;
        partial void OnAmountChanging(Nullable<global::System.Double> value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Driver_Id
        {
            get
            {
                return _Driver_Id;
            }
            set
            {
                OnDriver_IdChanging(value);
                ReportPropertyChanging("Driver_Id");
                _Driver_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Driver_Id");
                OnDriver_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Driver_Id;
        partial void OnDriver_IdChanging(Nullable<global::System.Int32> value);
        partial void OnDriver_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateDrawing
        {
            get
            {
                return _DateDrawing;
            }
            set
            {
                OnDateDrawingChanging(value);
                ReportPropertyChanging("DateDrawing");
                _DateDrawing = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateDrawing");
                OnDateDrawingChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateDrawing;
        partial void OnDateDrawingChanging(Nullable<global::System.DateTime> value);
        partial void OnDateDrawingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateOfArrival
        {
            get
            {
                return _DateOfArrival;
            }
            set
            {
                OnDateOfArrivalChanging(value);
                ReportPropertyChanging("DateOfArrival");
                _DateOfArrival = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfArrival");
                OnDateOfArrivalChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateOfArrival;
        partial void OnDateOfArrivalChanging(Nullable<global::System.DateTime> value);
        partial void OnDateOfArrivalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Canceled
        {
            get
            {
                return _Canceled;
            }
            set
            {
                OnCanceledChanging(value);
                ReportPropertyChanging("Canceled");
                _Canceled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Canceled");
                OnCanceledChanged();
            }
        }
        private Nullable<global::System.DateTime> _Canceled;
        partial void OnCanceledChanging(Nullable<global::System.DateTime> value);
        partial void OnCanceledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Drawer
        {
            get
            {
                return _Drawer;
            }
            set
            {
                OnDrawerChanging(value);
                ReportPropertyChanging("Drawer");
                _Drawer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Drawer");
                OnDrawerChanged();
            }
        }
        private global::System.String _Drawer;
        partial void OnDrawerChanging(global::System.String value);
        partial void OnDrawerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Car_Id
        {
            get
            {
                return _Car_Id;
            }
            set
            {
                OnCar_IdChanging(value);
                ReportPropertyChanging("Car_Id");
                _Car_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Car_Id");
                OnCar_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Car_Id;
        partial void OnCar_IdChanging(Nullable<global::System.Int32> value);
        partial void OnCar_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_DeliveryNotes_Buildings", "Building")]
        public Building Building
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Building>("SmartWorkingModel.FK_DeliveryNotes_Buildings", "Building").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Building>("SmartWorkingModel.FK_DeliveryNotes_Buildings", "Building").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Building> BuildingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Building>("SmartWorkingModel.FK_DeliveryNotes_Buildings", "Building");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Building>("SmartWorkingModel.FK_DeliveryNotes_Buildings", "Building", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_DeliveryNotes_Cars", "Car")]
        public Car Car
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Car>("SmartWorkingModel.FK_DeliveryNotes_Cars", "Car").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Car>("SmartWorkingModel.FK_DeliveryNotes_Cars", "Car").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Car> CarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Car>("SmartWorkingModel.FK_DeliveryNotes_Cars", "Car");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Car>("SmartWorkingModel.FK_DeliveryNotes_Cars", "Car", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_DeliveryNotes_Drivers", "Driver")]
        public Driver Driver
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Driver>("SmartWorkingModel.FK_DeliveryNotes_Drivers", "Driver").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Driver>("SmartWorkingModel.FK_DeliveryNotes_Drivers", "Driver").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Driver> DriverReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Driver>("SmartWorkingModel.FK_DeliveryNotes_Drivers", "Driver");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Driver>("SmartWorkingModel.FK_DeliveryNotes_Drivers", "Driver", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_DeliveryNotes_Recipes", "Recipe")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("SmartWorkingModel.FK_DeliveryNotes_Recipes", "Recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("SmartWorkingModel.FK_DeliveryNotes_Recipes", "Recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("SmartWorkingModel.FK_DeliveryNotes_Recipes", "Recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("SmartWorkingModel.FK_DeliveryNotes_Recipes", "Recipe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SmartWorkingModel", Name="Driver")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Driver : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Driver object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Driver CreateDriver(global::System.Int32 id)
        {
            Driver driver = new Driver();
            driver.Id = id;
            return driver;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Surname
        {
            get
            {
                return _Surname;
            }
            set
            {
                OnSurnameChanging(value);
                ReportPropertyChanging("Surname");
                _Surname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Surname");
                OnSurnameChanged();
            }
        }
        private global::System.String _Surname;
        partial void OnSurnameChanging(global::System.String value);
        partial void OnSurnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_DeliveryNotes_Drivers", "DeliveryNote")]
        public EntityCollection<DeliveryNote> DeliveryNotes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DeliveryNote>("SmartWorkingModel.FK_DeliveryNotes_Drivers", "DeliveryNote");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DeliveryNote>("SmartWorkingModel.FK_DeliveryNotes_Drivers", "DeliveryNote", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SmartWorkingModel", Name="Material")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Material : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Material object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Material CreateMaterial(global::System.Int32 id)
        {
            Material material = new Material();
            material.Id = id;
            return material;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InternalName
        {
            get
            {
                return _InternalName;
            }
            set
            {
                OnInternalNameChanging(value);
                ReportPropertyChanging("InternalName");
                _InternalName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InternalName");
                OnInternalNameChanged();
            }
        }
        private global::System.String _InternalName;
        partial void OnInternalNameChanging(global::System.String value);
        partial void OnInternalNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_MaterialStocks_Materails", "MaterialStock")]
        public EntityCollection<MaterialStock> MaterialStocks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MaterialStock>("SmartWorkingModel.FK_MaterialStocks_Materails", "MaterialStock");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MaterialStock>("SmartWorkingModel.FK_MaterialStocks_Materails", "MaterialStock", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_RecipeSpecifications_Materials", "RecipeSpecification")]
        public EntityCollection<RecipeSpecification> RecipeSpecifications
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipeSpecification>("SmartWorkingModel.FK_RecipeSpecifications_Materials", "RecipeSpecification");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipeSpecification>("SmartWorkingModel.FK_RecipeSpecifications_Materials", "RecipeSpecification", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SmartWorkingModel", Name="MaterialStock")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MaterialStock : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MaterialStock object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static MaterialStock CreateMaterialStock(global::System.Int32 id)
        {
            MaterialStock materialStock = new MaterialStock();
            materialStock.Id = id;
            return materialStock;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Material_Id
        {
            get
            {
                return _Material_Id;
            }
            set
            {
                OnMaterial_IdChanging(value);
                ReportPropertyChanging("Material_Id");
                _Material_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Material_Id");
                OnMaterial_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Material_Id;
        partial void OnMaterial_IdChanging(Nullable<global::System.Int32> value);
        partial void OnMaterial_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private Nullable<global::System.Double> _Amount;
        partial void OnAmountChanging(Nullable<global::System.Double> value);
        partial void OnAmountChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_MaterialStocks_Materails", "Material")]
        public Material Material
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SmartWorkingModel.FK_MaterialStocks_Materails", "Material").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SmartWorkingModel.FK_MaterialStocks_Materails", "Material").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Material> MaterialReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SmartWorkingModel.FK_MaterialStocks_Materails", "Material");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Material>("SmartWorkingModel.FK_MaterialStocks_Materails", "Material", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SmartWorkingModel", Name="Recipe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recipe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Recipe object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Recipe CreateRecipe(global::System.Int32 id)
        {
            Recipe recipe = new Recipe();
            recipe.Id = id;
            return recipe;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InternalName
        {
            get
            {
                return _InternalName;
            }
            set
            {
                OnInternalNameChanging(value);
                ReportPropertyChanging("InternalName");
                _InternalName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InternalName");
                OnInternalNameChanged();
            }
        }
        private global::System.String _InternalName;
        partial void OnInternalNameChanging(global::System.String value);
        partial void OnInternalNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_DeliveryNotes_Recipes", "DeliveryNote")]
        public EntityCollection<DeliveryNote> DeliveryNotes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DeliveryNote>("SmartWorkingModel.FK_DeliveryNotes_Recipes", "DeliveryNote");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DeliveryNote>("SmartWorkingModel.FK_DeliveryNotes_Recipes", "DeliveryNote", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_RecipeSpecifications_Recipes", "RecipeSpecification")]
        public EntityCollection<RecipeSpecification> RecipeSpecifications
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipeSpecification>("SmartWorkingModel.FK_RecipeSpecifications_Recipes", "RecipeSpecification");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipeSpecification>("SmartWorkingModel.FK_RecipeSpecifications_Recipes", "RecipeSpecification", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SmartWorkingModel", Name="RecipeSpecification")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RecipeSpecification : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RecipeSpecification object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static RecipeSpecification CreateRecipeSpecification(global::System.Int32 id)
        {
            RecipeSpecification recipeSpecification = new RecipeSpecification();
            recipeSpecification.Id = id;
            return recipeSpecification;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Material_Id
        {
            get
            {
                return _Material_Id;
            }
            set
            {
                OnMaterial_IdChanging(value);
                ReportPropertyChanging("Material_Id");
                _Material_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Material_Id");
                OnMaterial_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Material_Id;
        partial void OnMaterial_IdChanging(Nullable<global::System.Int32> value);
        partial void OnMaterial_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Recipe_Id
        {
            get
            {
                return _Recipe_Id;
            }
            set
            {
                OnRecipe_IdChanging(value);
                ReportPropertyChanging("Recipe_Id");
                _Recipe_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Recipe_Id");
                OnRecipe_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Recipe_Id;
        partial void OnRecipe_IdChanging(Nullable<global::System.Int32> value);
        partial void OnRecipe_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private Nullable<global::System.Double> _Amount;
        partial void OnAmountChanging(Nullable<global::System.Double> value);
        partial void OnAmountChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_RecipeSpecifications_Materials", "Material")]
        public Material Material
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SmartWorkingModel.FK_RecipeSpecifications_Materials", "Material").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SmartWorkingModel.FK_RecipeSpecifications_Materials", "Material").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Material> MaterialReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Material>("SmartWorkingModel.FK_RecipeSpecifications_Materials", "Material");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Material>("SmartWorkingModel.FK_RecipeSpecifications_Materials", "Material", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SmartWorkingModel", "FK_RecipeSpecifications_Recipes", "Recipe")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("SmartWorkingModel.FK_RecipeSpecifications_Recipes", "Recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("SmartWorkingModel.FK_RecipeSpecifications_Recipes", "Recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("SmartWorkingModel.FK_RecipeSpecifications_Recipes", "Recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("SmartWorkingModel.FK_RecipeSpecifications_Recipes", "Recipe", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
