//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SmartWorking.Office.PrimitiveEntities
{
    public partial class DeliveryNotePrimitive : IPrimitive
    {
        #region Primitive Properties
    		public int Id
    		{
            get;
            set;
    		}
    		public virtual Nullable<int> Building_Id
    		{
    			get;
    			set;
    		}
    		public virtual Nullable<int> Recipe_Id
    		{
    			get;
    			set;
    		}
    		public Nullable<double> Amount
    		{
            get;
            set;
    		}
    		public virtual Nullable<int> Driver_Id
    		{
    			get;
    			set;
    		}
    		public Nullable<System.DateTime> DateDrawing
    		{
            get;
            set;
    		}
    		public Nullable<System.DateTime> DateOfArrival
    		{
            get;
            set;
    		}
    		public Nullable<System.DateTime> Canceled
    		{
            get;
            set;
    		}
    		public string Drawer
    		{
            get;
            set;
    		}
    		public virtual Nullable<int> Car_Id
    		{
    			get;
    			set;
    		}

        #endregion
    }
    
}
