//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using SmartWorking.Office.PrimitiveEntities;

namespace SmartWorking.Office.Entities
{
    public partial class DeliveryNote : DeliveryNotePrimitive
    {
        #region Primitive Properties
    		public override Nullable<int> Driver_Id
    		{
            get { return _driver_Id; }
            set
            {        
                try
                {
                    _settingFK = true;
                    if (_driver_Id != value)
                    {
                        if (Driver != null && Driver.Id != value)
                        {
                            Driver = null;
                        }
                        _driver_Id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
    		}
    		private Nullable<int> _driver_Id;    
    
    		public override Nullable<int> Car_Id
    		{
            get { return _car_Id; }
            set
            {        
                try
                {
                    _settingFK = true;
                    if (_car_Id != value)
                    {
                        if (Car != null && Car.Id != value)
                        {
                            Car = null;
                        }
                        _car_Id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
    		}
    		private Nullable<int> _car_Id;    
    
    		public override Nullable<int> Order_Id
    		{
            get { return _order_Id; }
            set
            {        
                try
                {
                    _settingFK = true;
                    if (_order_Id != value)
                    {
                        if (Order != null && Order.Id != value)
                        {
                            Order = null;
                        }
                        _order_Id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
    		}
    		private Nullable<int> _order_Id;    
    

        #endregion
        #region Navigation Properties
    
        public Driver Driver
        {
            get { return _driver; }
            set
            {
                if (!ReferenceEquals(_driver, value))
                {
                    var previousValue = _driver;
                    _driver = value;
                    FixupDriver(previousValue);
                }
            }
        }
        private Driver _driver;
    
        public Car Car
        {
            get { return _car; }
            set
            {
                if (!ReferenceEquals(_car, value))
                {
                    var previousValue = _car;
                    _car = value;
                    FixupCar(previousValue);
                }
            }
        }
        private Car _car;
    
        public Order Order
        {
            get { return _order; }
            set
            {
                if (!ReferenceEquals(_order, value))
                {
                    var previousValue = _order;
                    _order = value;
                    FixupOrder(previousValue);
                }
            }
        }
        private Order _order;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupDriver(Driver previousValue)
        {
            if (previousValue != null && previousValue.DeliveryNotes.Contains(this))
            {
                previousValue.DeliveryNotes.Remove(this);
            }
    
            if (Driver != null)
            {
                if (!Driver.DeliveryNotes.Contains(this))
                {
                    Driver.DeliveryNotes.Add(this);
                }
                if (Driver_Id != Driver.Id)
                {
                    Driver_Id = Driver.Id;
                }
            }
            else if (!_settingFK)
            {
                Driver_Id = null;
            }
        }
    
        private void FixupCar(Car previousValue)
        {
            if (previousValue != null && previousValue.DeliveryNotes.Contains(this))
            {
                previousValue.DeliveryNotes.Remove(this);
            }
    
            if (Car != null)
            {
                if (!Car.DeliveryNotes.Contains(this))
                {
                    Car.DeliveryNotes.Add(this);
                }
                if (Car_Id != Car.Id)
                {
                    Car_Id = Car.Id;
                }
            }
            else if (!_settingFK)
            {
                Car_Id = null;
            }
        }
    
        private void FixupOrder(Order previousValue)
        {
            if (previousValue != null && previousValue.DeliveryNotes.Contains(this))
            {
                previousValue.DeliveryNotes.Remove(this);
            }
    
            if (Order != null)
            {
                if (!Order.DeliveryNotes.Contains(this))
                {
                    Order.DeliveryNotes.Add(this);
                }
                if (Order_Id != Order.Id)
                {
                    Order_Id = Order.Id;
                }
            }
            else if (!_settingFK)
            {
                Order_Id = null;
            }
        }

        #endregion
    }
}
