//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SmartWorking.Office.Entities
{
    public partial class DeliveryNote : DeliveryNotePrimitive
    {
        #region Primitive Properties
    		public override Nullable<int> Building_Id
    		{
            get { return _building_Id; }
            set
            {        
                try
                {
                    _settingFK = true;
                    if (_building_Id != value)
                    {
                        if (Building != null && Building.Id != value)
                        {
                            Building = null;
                        }
                        _building_Id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
    		}
    		private Nullable<int> _building_Id;    
    
    		public override Nullable<int> Recipe_Id
    		{
            get { return _recipe_Id; }
            set
            {        
                try
                {
                    _settingFK = true;
                    if (_recipe_Id != value)
                    {
                        if (Recipe != null && Recipe.Id != value)
                        {
                            Recipe = null;
                        }
                        _recipe_Id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
    		}
    		private Nullable<int> _recipe_Id;    
    
    		public override Nullable<int> Driver_Id
    		{
            get { return _driver_Id; }
            set
            {        
                try
                {
                    _settingFK = true;
                    if (_driver_Id != value)
                    {
                        if (Driver != null && Driver.Id != value)
                        {
                            Driver = null;
                        }
                        _driver_Id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
    		}
    		private Nullable<int> _driver_Id;    
    
    		public override Nullable<int> Car_Id
    		{
            get { return _car_Id; }
            set
            {        
                try
                {
                    _settingFK = true;
                    if (_car_Id != value)
                    {
                        if (Car != null && Car.Id != value)
                        {
                            Car = null;
                        }
                        _car_Id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
    		}
    		private Nullable<int> _car_Id;    
    

        #endregion
        #region Navigation Properties
    
        public Building Building
        {
            get { return _building; }
            set
            {
                if (!ReferenceEquals(_building, value))
                {
                    var previousValue = _building;
                    _building = value;
                    FixupBuilding(previousValue);
                }
            }
        }
        private Building _building;
    
        public Car Car
        {
            get { return _car; }
            set
            {
                if (!ReferenceEquals(_car, value))
                {
                    var previousValue = _car;
                    _car = value;
                    FixupCar(previousValue);
                }
            }
        }
        private Car _car;
    
        public Driver Driver
        {
            get { return _driver; }
            set
            {
                if (!ReferenceEquals(_driver, value))
                {
                    var previousValue = _driver;
                    _driver = value;
                    FixupDriver(previousValue);
                }
            }
        }
        private Driver _driver;
    
        public Recipe Recipe
        {
            get { return _recipe; }
            set
            {
                if (!ReferenceEquals(_recipe, value))
                {
                    var previousValue = _recipe;
                    _recipe = value;
                    FixupRecipe(previousValue);
                }
            }
        }
        private Recipe _recipe;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupBuilding(Building previousValue)
        {
            if (previousValue != null && previousValue.DeliveryNotes.Contains(this))
            {
                previousValue.DeliveryNotes.Remove(this);
            }
    
            if (Building != null)
            {
                if (!Building.DeliveryNotes.Contains(this))
                {
                    Building.DeliveryNotes.Add(this);
                }
                if (Building_Id != Building.Id)
                {
                    Building_Id = Building.Id;
                }
            }
            else if (!_settingFK)
            {
                Building_Id = null;
            }
        }
    
        private void FixupCar(Car previousValue)
        {
            if (previousValue != null && previousValue.DeliveryNotes.Contains(this))
            {
                previousValue.DeliveryNotes.Remove(this);
            }
    
            if (Car != null)
            {
                if (!Car.DeliveryNotes.Contains(this))
                {
                    Car.DeliveryNotes.Add(this);
                }
                if (Car_Id != Car.Id)
                {
                    Car_Id = Car.Id;
                }
            }
            else if (!_settingFK)
            {
                Car_Id = null;
            }
        }
    
        private void FixupDriver(Driver previousValue)
        {
            if (previousValue != null && previousValue.DeliveryNotes.Contains(this))
            {
                previousValue.DeliveryNotes.Remove(this);
            }
    
            if (Driver != null)
            {
                if (!Driver.DeliveryNotes.Contains(this))
                {
                    Driver.DeliveryNotes.Add(this);
                }
                if (Driver_Id != Driver.Id)
                {
                    Driver_Id = Driver.Id;
                }
            }
            else if (!_settingFK)
            {
                Driver_Id = null;
            }
        }
    
        private void FixupRecipe(Recipe previousValue)
        {
            if (previousValue != null && previousValue.DeliveryNotes.Contains(this))
            {
                previousValue.DeliveryNotes.Remove(this);
            }
    
            if (Recipe != null)
            {
                if (!Recipe.DeliveryNotes.Contains(this))
                {
                    Recipe.DeliveryNotes.Add(this);
                }
                if (Recipe_Id != Recipe.Id)
                {
                    Recipe_Id = Recipe.Id;
                }
            }
            else if (!_settingFK)
            {
                Recipe_Id = null;
            }
        }

        #endregion
    }
}
