//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SmartWorking.Office.Entities
{
    public partial class DriverPrimitive
    {
        #region Primitive Properties
    		public int Id
    		{
            get;
            set;
    		}
    		public string Name
    		{
            get;
            set;
    		}
    		public string Surname
    		{
            get;
            set;
    		}
    		public string Phone
    		{
            get;
            set;
    		}

        #endregion
    }
    
}
