
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SmartWorking.Office.Entities
{
    public static class GetEntityHelper 
    {
        public static Building GetEntity(this BuildingPrimitive primitive)
        {
        		Building result = new Building(); 
        
        		result.Id = primitive.Id;
        		
        		result.Contractor_Id = primitive.Contractor_Id;
        		
        		result.City = primitive.City;
        		
        		result.Street = primitive.Street;
        		
        		result.HouseNo = primitive.HouseNo;
        		
        		return result;
        }
        
        public static Car GetEntity(this CarPrimitive primitive)
        {
        		Car result = new Car(); 
        
        		result.Id = primitive.Id;
        		
        		result.RegistrationNumber = primitive.RegistrationNumber;
        		
        		result.Name = primitive.Name;
        		
        		result.InternalName = primitive.InternalName;
        		
        		return result;
        }
        
        public static Contractor GetEntity(this ContractorPrimitive primitive)
        {
        		Contractor result = new Contractor(); 
        
        		result.Id = primitive.Id;
        		
        		result.FullName = primitive.FullName;
        		
        		result.Name = primitive.Name;
        		
        		result.Surname = primitive.Surname;
        		
        		result.Phone = primitive.Phone;
        		
        		return result;
        }
        
        public static DeliveryNote GetEntity(this DeliveryNotePrimitive primitive)
        {
        		DeliveryNote result = new DeliveryNote(); 
        
        		result.Id = primitive.Id;
        		
        		result.Building_Id = primitive.Building_Id;
        		
        		result.Recipe_Id = primitive.Recipe_Id;
        		
        		result.Amount = primitive.Amount;
        		
        		result.Driver_Id = primitive.Driver_Id;
        		
        		result.DateDrawing = primitive.DateDrawing;
        		
        		result.DateOfArrival = primitive.DateOfArrival;
        		
        		result.Canceled = primitive.Canceled;
        		
        		result.Drawer = primitive.Drawer;
        		
        		result.Car_Id = primitive.Car_Id;
        		
        		return result;
        }
        
        public static Driver GetEntity(this DriverPrimitive primitive)
        {
        		Driver result = new Driver(); 
        
        		result.Id = primitive.Id;
        		
        		result.Name = primitive.Name;
        		
        		result.Surname = primitive.Surname;
        		
        		result.Phone = primitive.Phone;
        		
        		return result;
        }
        
        public static Material GetEntity(this MaterialPrimitive primitive)
        {
        		Material result = new Material(); 
        
        		result.Id = primitive.Id;
        		
        		result.Name = primitive.Name;
        		
        		result.InternalName = primitive.InternalName;
        		
        		return result;
        }
        
        public static MaterialStock GetEntity(this MaterialStockPrimitive primitive)
        {
        		MaterialStock result = new MaterialStock(); 
        
        		result.Id = primitive.Id;
        		
        		result.Material_Id = primitive.Material_Id;
        		
        		result.Amount = primitive.Amount;
        		
        		return result;
        }
        
        public static Recipe GetEntity(this RecipePrimitive primitive)
        {
        		Recipe result = new Recipe(); 
        
        		result.Id = primitive.Id;
        		
        		result.Name = primitive.Name;
        		
        		result.InternalName = primitive.InternalName;
        		
        		return result;
        }
        
        public static RecipeComponent GetEntity(this RecipeComponentPrimitive primitive)
        {
        		RecipeComponent result = new RecipeComponent(); 
        
        		result.Id = primitive.Id;
        		
        		result.Material_Id = primitive.Material_Id;
        		
        		result.Recipe_Id = primitive.Recipe_Id;
        		
        		result.Amount = primitive.Amount;
        		
        		return result;
        }
        
    }
}
