//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SmartWorking.Office.Entities
{
    public partial class Material : MaterialPrimitive
    {
        #region Navigation Properties
    
        public ICollection<MaterialStock> MaterialStocks
        {
            get
            {
                if (_materialStocks == null)
                {
                    var newCollection = new FixupCollection<MaterialStock>();
                    newCollection.CollectionChanged += FixupMaterialStocks;
                    _materialStocks = newCollection;
                }
                return _materialStocks;
            }
            set
            {
                if (!ReferenceEquals(_materialStocks, value))
                {
                    var previousValue = _materialStocks as FixupCollection<MaterialStock>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMaterialStocks;
                    }
                    _materialStocks = value;
                    var newValue = value as FixupCollection<MaterialStock>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMaterialStocks;
                    }
                }
            }
        }
        private ICollection<MaterialStock> _materialStocks;
    
        public ICollection<RecipeComponent> RecipeComponents
        {
            get
            {
                if (_recipeComponents == null)
                {
                    var newCollection = new FixupCollection<RecipeComponent>();
                    newCollection.CollectionChanged += FixupRecipeComponents;
                    _recipeComponents = newCollection;
                }
                return _recipeComponents;
            }
            set
            {
                if (!ReferenceEquals(_recipeComponents, value))
                {
                    var previousValue = _recipeComponents as FixupCollection<RecipeComponent>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRecipeComponents;
                    }
                    _recipeComponents = value;
                    var newValue = value as FixupCollection<RecipeComponent>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRecipeComponents;
                    }
                }
            }
        }
        private ICollection<RecipeComponent> _recipeComponents;

        #endregion
        #region Association Fixup
    
        private void FixupMaterialStocks(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (MaterialStock item in e.NewItems)
                {
                    item.Material = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MaterialStock item in e.OldItems)
                {
                    if (ReferenceEquals(item.Material, this))
                    {
                        item.Material = null;
                    }
                }
            }
        }
    
        private void FixupRecipeComponents(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (RecipeComponent item in e.NewItems)
                {
                    item.Material = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (RecipeComponent item in e.OldItems)
                {
                    if (ReferenceEquals(item.Material, this))
                    {
                        item.Material = null;
                    }
                }
            }
        }

        #endregion
    }
}
