//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SmartWorking.Office.PrimitiveEntities
{
    public partial class MaterialPrimitive : PrimitiveBase
    {
        #region Primitive Properties
    		public string Name
    		{
            get;
            set;
    		}
    		public virtual Nullable<int> Producer_Id
    		{
    			get;
    			set;
    		}
    		public virtual Nullable<int> Deliverer_Id
    		{
    			get;
    			set;
    		}
    		public string InternalName
    		{
            get;
            set;
    		}
    		public Nullable<int> MaterialType
    		{
            get;
            set;
    		}

        #endregion
    }
    
}
