//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace SmartWorking.Office.PrimitiveEntities.MetaDates
{
    
    
    public class MaterialMetaDataBase
    {
        [Required]
        public virtual int Id
        {
            get;
            set;
        }
    	
        [StringLength(150, ErrorMessage="Ce champ ne peut depasser 150 caracteres")]
        public virtual string Name
        {
            get;
            set;
        }
        public virtual Nullable<int> Producer_Id
        {
            get;
            set;
    
        }
        public virtual Nullable<int> Deliverer_Id
        {
            get;
            set;
    
        }
    	
        [StringLength(50, ErrorMessage="Ce champ ne peut depasser 50 caracteres")]
        public virtual string InternalName
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> Deleted
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> Deactivated
        {
            get;
            set;
        }
        public virtual Nullable<int> MaterialType
        {
            get;
            set;
        }
    }
}
