//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SmartWorking.Office.Entities
{
    public partial class RecipeComponent
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public Nullable<int> Material_Id
        {
            get { return _material_Id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_material_Id != value)
                    {
                        if (Material != null && Material.Id != value)
                        {
                            Material = null;
                        }
                        _material_Id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _material_Id;
    
        public Nullable<int> Recipe_Id
        {
            get { return _recipe_Id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_recipe_Id != value)
                    {
                        if (Recipe != null && Recipe.Id != value)
                        {
                            Recipe = null;
                        }
                        _recipe_Id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _recipe_Id;
    
        public Nullable<double> Amount
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public Material Material
        {
            get { return _material; }
            set
            {
                if (!ReferenceEquals(_material, value))
                {
                    var previousValue = _material;
                    _material = value;
                    FixupMaterial(previousValue);
                }
            }
        }
        private Material _material;
    
        public Recipe Recipe
        {
            get { return _recipe; }
            set
            {
                if (!ReferenceEquals(_recipe, value))
                {
                    var previousValue = _recipe;
                    _recipe = value;
                    FixupRecipe(previousValue);
                }
            }
        }
        private Recipe _recipe;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupMaterial(Material previousValue)
        {
            if (previousValue != null && previousValue.RecipeComponents.Contains(this))
            {
                previousValue.RecipeComponents.Remove(this);
            }
    
            if (Material != null)
            {
                if (!Material.RecipeComponents.Contains(this))
                {
                    Material.RecipeComponents.Add(this);
                }
                if (Material_Id != Material.Id)
                {
                    Material_Id = Material.Id;
                }
            }
            else if (!_settingFK)
            {
                Material_Id = null;
            }
        }
    
        private void FixupRecipe(Recipe previousValue)
        {
            if (previousValue != null && previousValue.RecipeComponents.Contains(this))
            {
                previousValue.RecipeComponents.Remove(this);
            }
    
            if (Recipe != null)
            {
                if (!Recipe.RecipeComponents.Contains(this))
                {
                    Recipe.RecipeComponents.Add(this);
                }
                if (Recipe_Id != Recipe.Id)
                {
                    Recipe_Id = Recipe.Id;
                }
            }
            else if (!_settingFK)
            {
                Recipe_Id = null;
            }
        }

        #endregion
    }
}
