//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template made by Louis-Guillaume Morand.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using SmartWorking.Office.PrimitiveEntities.Properties;

namespace SmartWorking.Office.PrimitiveEntities.MetaDates
{
    
    
    public class RecipeMetaData
    {
        [Required]
        public virtual int Id
        {
            get;
            set;
        }
    	
        [StringLength(70, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "RecipeMetaData_Name_StringLength_70")]
        public virtual string Name
        {
            get;
            set;
        }
    	
        [StringLength(50, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "RecipeMetaData_InternalName_StringLength_50")]
        public virtual string InternalName
        {
            get;
            set;
        }
    	
        [StringLength(10, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "RecipeMetaData_Number_StringLength_10")]
        public virtual string Number
        {
            get;
            set;
        }
    	
        [StringLength(10, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "RecipeMetaData_Granulation_StringLength_10")]
        public virtual string Granulation
        {
            get;
            set;
        }
    	
        [StringLength(10, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "RecipeMetaData_Consistency_StringLength_10")]
        public virtual string Consistency
        {
            get;
            set;
        }
    	
        [StringLength(10, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "RecipeMetaData_ConcreteClass_StringLength_10")]
        public virtual string ConcreteClass
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> Deleted
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> Deactivated
        {
            get;
            set;
        }
    	
        [StringLength(20, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "RecipeMetaData_WaterToCement_StringLength_20")]
        public virtual string WaterToCement
        {
            get;
            set;
        }
    	
        [StringLength(20, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "RecipeMetaData_StrengthClass_StringLength_20")]
        public virtual string StrengthClass
        {
            get;
            set;
        }
        public virtual Nullable<int> StrengthProgress
        {
            get;
            set;
        }
    	
        [StringLength(20, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "RecipeMetaData_Code_StringLength_20")]
        public virtual string Code
        {
            get;
            set;
        }
    }
}
