//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using SmartWorking.Office.PrimitiveEntities;

namespace SmartWorking.Office.Entities
{
    public partial class Recipe : RecipePrimitive
    {
        #region Navigation Properties
    
        public ICollection<RecipeComponent> RecipeComponents
        {
            get
            {
                if (_recipeComponents == null)
                {
                    var newCollection = new FixupCollection<RecipeComponent>();
                    newCollection.CollectionChanged += FixupRecipeComponents;
                    _recipeComponents = newCollection;
                }
                return _recipeComponents;
            }
            set
            {
                if (!ReferenceEquals(_recipeComponents, value))
                {
                    var previousValue = _recipeComponents as FixupCollection<RecipeComponent>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRecipeComponents;
                    }
                    _recipeComponents = value;
                    var newValue = value as FixupCollection<RecipeComponent>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRecipeComponents;
                    }
                }
            }
        }
        private ICollection<RecipeComponent> _recipeComponents;
    
        public ICollection<Order> Orders
        {
            get
            {
                if (_orders == null)
                {
                    var newCollection = new FixupCollection<Order>();
                    newCollection.CollectionChanged += FixupOrders;
                    _orders = newCollection;
                }
                return _orders;
            }
            set
            {
                if (!ReferenceEquals(_orders, value))
                {
                    var previousValue = _orders as FixupCollection<Order>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupOrders;
                    }
                    _orders = value;
                    var newValue = value as FixupCollection<Order>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupOrders;
                    }
                }
            }
        }
        private ICollection<Order> _orders;

        #endregion
        #region Association Fixup
    
        private void FixupRecipeComponents(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (RecipeComponent item in e.NewItems)
                {
                    item.Recipe = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (RecipeComponent item in e.OldItems)
                {
                    if (ReferenceEquals(item.Recipe, this))
                    {
                        item.Recipe = null;
                    }
                }
            }
        }
    
        private void FixupOrders(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Order item in e.NewItems)
                {
                    item.Recipe = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Order item in e.OldItems)
                {
                    if (ReferenceEquals(item.Recipe, this))
                    {
                        item.Recipe = null;
                    }
                }
            }
        }

        #endregion
    }
}
