//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SmartWorking.Office.Entities
{
    public partial class Recipe
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string InternalName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<DeliveryNote> DeliveryNotes
        {
            get
            {
                if (_deliveryNotes == null)
                {
                    var newCollection = new FixupCollection<DeliveryNote>();
                    newCollection.CollectionChanged += FixupDeliveryNotes;
                    _deliveryNotes = newCollection;
                }
                return _deliveryNotes;
            }
            set
            {
                if (!ReferenceEquals(_deliveryNotes, value))
                {
                    var previousValue = _deliveryNotes as FixupCollection<DeliveryNote>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupDeliveryNotes;
                    }
                    _deliveryNotes = value;
                    var newValue = value as FixupCollection<DeliveryNote>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupDeliveryNotes;
                    }
                }
            }
        }
        private ICollection<DeliveryNote> _deliveryNotes;
    
        public virtual ICollection<RecipeSpecification> RecipeSpecifications
        {
            get
            {
                if (_recipeSpecifications == null)
                {
                    var newCollection = new FixupCollection<RecipeSpecification>();
                    newCollection.CollectionChanged += FixupRecipeSpecifications;
                    _recipeSpecifications = newCollection;
                }
                return _recipeSpecifications;
            }
            set
            {
                if (!ReferenceEquals(_recipeSpecifications, value))
                {
                    var previousValue = _recipeSpecifications as FixupCollection<RecipeSpecification>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRecipeSpecifications;
                    }
                    _recipeSpecifications = value;
                    var newValue = value as FixupCollection<RecipeSpecification>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRecipeSpecifications;
                    }
                }
            }
        }
        private ICollection<RecipeSpecification> _recipeSpecifications;

        #endregion
        #region Association Fixup
    
        private void FixupDeliveryNotes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (DeliveryNote item in e.NewItems)
                {
                    item.Recipe = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (DeliveryNote item in e.OldItems)
                {
                    if (ReferenceEquals(item.Recipe, this))
                    {
                        item.Recipe = null;
                    }
                }
            }
        }
    
        private void FixupRecipeSpecifications(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (RecipeSpecification item in e.NewItems)
                {
                    item.Recipe = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (RecipeSpecification item in e.OldItems)
                {
                    if (ReferenceEquals(item.Recipe, this))
                    {
                        item.Recipe = null;
                    }
                }
            }
        }

        #endregion
    }
}
