//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SmartWorking.Office.PrimitiveEntities
{
    public partial class RecipePrimitive : PrimitiveBase
    {
        #region Primitive Properties
    		public string Name
    		{
            get;
            set;
    		}
    		public string InternalName
    		{
            get;
            set;
    		}
    		public string Number
    		{
            get;
            set;
    		}
    		public string Granulation
    		{
            get;
            set;
    		}
    		public string Consistency
    		{
            get;
            set;
    		}
    		public string ConcreteClass
    		{
            get;
            set;
    		}
    		public Nullable<System.DateTime> Deleted
    		{
            get;
            set;
    		}
    		public Nullable<int> IsActive
    		{
            get;
            set;
    		}

        #endregion
    }
    
}
