//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.EntityClient;
using System.Data.Objects;
using SmartWorking.Office.Entities;

namespace SmartWorking.Office.Services.Hosting.Local
{
  public class SmartWorkingEntities : ObjectContext
  {
    public const string ConnectionString = "name=SmartWorkingEntities";
    public const string ContainerName = "SmartWorkingEntities";

    #region Constructors

    public SmartWorkingEntities()
      : base(ConnectionString, ContainerName)
    {
      ContextOptions.LazyLoadingEnabled = false;
    }

    public SmartWorkingEntities(string connectionString)
      : base(connectionString, ContainerName)
    {
      ContextOptions.LazyLoadingEnabled = false;
    }

    public SmartWorkingEntities(EntityConnection connection)
      : base(connection, ContainerName)
    {
      ContextOptions.LazyLoadingEnabled = false;
    }

    #endregion

    #region ObjectSet Properties

    private ObjectSet<Building> _buildings;

    private ObjectSet<Car> _cars;

    private ObjectSet<Contractor> _contractors;

    private ObjectSet<DeliveryNote> _deliveryNotes;

    private ObjectSet<Driver> _drivers;
    private ObjectSet<MaterialStock> _materialStocks;

    private ObjectSet<Material> _materials;
    private ObjectSet<RecipeSpecification> _recipeSpecifications;
    private ObjectSet<Recipe> _recipes;

    public ObjectSet<Building> Buildings
    {
      get { return _buildings ?? (_buildings = CreateObjectSet<Building>("Buildings")); }
    }

    public ObjectSet<Car> Cars
    {
      get { return _cars ?? (_cars = CreateObjectSet<Car>("Cars")); }
    }

    public ObjectSet<Contractor> Contractors
    {
      get { return _contractors ?? (_contractors = CreateObjectSet<Contractor>("Contractors")); }
    }

    public ObjectSet<DeliveryNote> DeliveryNotes
    {
      get { return _deliveryNotes ?? (_deliveryNotes = CreateObjectSet<DeliveryNote>("DeliveryNotes")); }
    }

    public ObjectSet<Driver> Drivers
    {
      get { return _drivers ?? (_drivers = CreateObjectSet<Driver>("Drivers")); }
    }

    public ObjectSet<Material> Materials
    {
      get { return _materials ?? (_materials = CreateObjectSet<Material>("Materials")); }
    }

    public ObjectSet<MaterialStock> MaterialStocks
    {
      get { return _materialStocks ?? (_materialStocks = CreateObjectSet<MaterialStock>("MaterialStocks")); }
    }

    public ObjectSet<Recipe> Recipes
    {
      get { return _recipes ?? (_recipes = CreateObjectSet<Recipe>("Recipes")); }
    }

    public ObjectSet<RecipeSpecification> RecipeSpecifications
    {
      get
      {
        return _recipeSpecifications ??
               (_recipeSpecifications = CreateObjectSet<RecipeSpecification>("RecipeSpecifications"));
      }
    }

    #endregion
  }
}