//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using SmartWorking.Office.PrimitiveEntities.MetaDates;

namespace SmartWorking.Office.PrimitiveEntities
{
    [MetadataType(typeof(UserMetaData))]
    public partial class UserPrimitive : PrimitiveBase
    {
        #region Primitive Properties
    		public string Name
    		{
            get;
            set;
    		}
    		public string Surname
    		{
            get;
            set;
    		}
    		public string Password
    		{
            get;
            set;
    		}
    		public string PasswordSalz
    		{
            get;
            set;
    		}
    		public string Phone
    		{
            get;
            set;
    		}

        #endregion
    }
    
}
